In [1]:
#importar principais bases para análise de dados
import pandas as pd
import plotly.express as px
import plotly.offline as po
import os
import numpy as np

#importando bases para acessar o sap
import win32com.client
import sys
import subprocess
from datetime import datetime

In [1]:
#inicializar variáveis do SAP
SapGuiAuto = win32com.client.GetObject('SAPGUI')
application = SapGuiAuto.GetScriptingEngine
connection = application.Children(0)
session = connection.Children(0)
noew = datetime.now()

NameError: name 'win32com' is not defined

In [3]:
#iniciar a transação do SAP (script)
session.findById("wnd[0]").maximize
session.findById("wnd[0]/tbar[0]/okcd").text = "/NZPM301"
session.findById("wnd[0]").sendVKey(0)
session.findById("wnd[0]/usr/cmbP_AREAP").key = "I"
session.findById("wnd[0]/usr/ctxtS_CDSRE-LOW").text = ""
session.findById("wnd[0]/usr/ctxtS_BUKRS-LOW").text = "CSPC"
session.findById("wnd[0]/usr/ctxtS_WERKS-LOW").text = "2100"
session.findById("wnd[0]/usr/ctxtS_STSRE-LOW").text = "19"
session.findById("wnd[0]/tbar[1]/btn[8]").press()

In [4]:
#encerrar SAP Scriptsession
connection = None
application = None
SapGuiAuto = None

In [40]:
#ler arquivo e criar tabela
caminho = ("C:\Python\export.xlsx")
dados = pd.read_excel(caminho)
cabecalho = ["Código do Status SRE","NF Remessa","Código da CRE","Nome do Fornecedor","Dias no Fornecedor","Material"]
dados = dados[
dados = dados.sort_values("Dias no Fornecedor",ascending=False)
display(dados)

KeyError: "['Nome do Fornecedor'] not in index"

In [6]:
#fazer análise dos dados


#contar número de notas
n_linhas = dados.shape[0]
print("--------------------------------------")
print("Número de notas pendentes:", n_linhas)
print("--------------------------------------")

#media de dias no fornecedor
sum_dias = dados["Dias no Fornecedor"].sum(axis=0)
media_dias = round(sum_dias/n_linhas)
print("Média de dias no fornecedor:", media_dias)
print("--------------------------------------")

#grifando valores acima de 300
def highlight(cell):
    if type(cell) != str and cell > 300 :
        return 'background-color: lightcoral'
    else:
        return 'color: black'

display(dados.style.applymap(highlight, subset = pd.IndexSlice[:,["Dias no Fornecedor"]]))

--------------------------------------
Número de notas pendentes: 51
--------------------------------------
Média de dias no fornecedor: 187
--------------------------------------

In [39]:
#extraindo valores das colunas
cabecalho = dados.head(0)
nomes_colunas = []

for i in dados.head(0):
    nomes_colunas.append(i)

['Código do Status SRE',
 'NF Remessa',
 'Código da CRE',
 'Nome\xa0do Fornecedor',
 'Dias no Fornecedor',
 'Material']

In [ ]:
from tkinter import *
from tkinter import ttk
 
root = Tk()
root.geometry("800x800")

style = ttk.Style()
style.theme_use('clam')

#criando colunas
tree = ttk.Treeview(root,)




#criando as colunas teste
tree = ttk.Treeview(root, column=('Código do Status','NF','Código da CRE'), show = 'headings', height = 5)
tree.column("# 1", anchor=CENTER)
tree.heading("# 1", text="Código do Status")
tree.column("# 2", anchor=CENTER)
tree.heading("# 2", text="NF")
tree.column("# 3", anchor=CENTER)
tree.heading("# 3", text="Código da CRE")

#inserindo os valores

#tree.insert('', 'end', text="1", values=('Amit', 'Kumar', '17701'))
#tree.insert('', 'end', text="1", values=('Ankush', 'Mathur', '17702'))

#configurando titulo
titulo = tk.Label(root, text = "Acompanhamento de notas")
titulo.pack(padx = 5, pady = 5)
font_titulo = ("Helvetica",20,"bold")
titulo.configure(font = font_titulo)

tree.pack()

root.mainloop()